CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    FullName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    Role NVARCHAR(20) NOT NULL, -- 'Admin' or 'Alumni'
    Phone NVARCHAR(20),
    ProfilePic NVARCHAR(MAX),
    Bio NVARCHAR(MAX),
    BatchYear INT,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Education (
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    Degree NVARCHAR(100),
    Branch NVARCHAR(100),
    Institute NVARCHAR(100),
    GraduationYear INT
);

CREATE TABLE ProfessionalExperience (
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    Company NVARCHAR(100),
    Title NVARCHAR(100),
    Industry NVARCHAR(100),
    StartDate DATE,
    EndDate DATE
);

CREATE TABLE JobPostings (
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE SET NULL,
    Title NVARCHAR(100),
    Company NVARCHAR(100),
    Location NVARCHAR(100),
    Description NVARCHAR(MAX),
    PostedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Events (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(100),
    Description NVARCHAR(MAX),
    EventDate DATETIME,
    Location NVARCHAR(200),
    CreatedBy INT FOREIGN KEY REFERENCES Users(Id) ON DELETE SET NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE RSVPs (
    Id INT PRIMARY KEY IDENTITY(1,1),
    EventId INT FOREIGN KEY REFERENCES Events(Id) ON DELETE CASCADE,
    UserId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    RSVPDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE Announcements (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(200),
    Message NVARCHAR(MAX),
    CreatedBy INT FOREIGN KEY REFERENCES Users(Id) ON DELETE SET NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Messages (
    Id INT PRIMARY KEY IDENTITY(1,1),
    SenderId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    ReceiverId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    Content NVARCHAR(MAX) NOT NULL,
    SentAt DATETIME DEFAULT GETDATE(),
    IsRead BIT DEFAULT 0
);

CREATE TABLE Messages (
    Id INT PRIMARY KEY IDENTITY(1,1),
    SenderId INT NOT NULL,
    ReceiverId INT NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    SentAt DATETIME DEFAULT GETDATE(),
    IsRead BIT DEFAULT 0,

    CONSTRAINT FK_Messages_Sender FOREIGN KEY (SenderId) REFERENCES Users(Id) ON DELETE CASCADE,
    CONSTRAINT FK_Messages_Receiver FOREIGN KEY (ReceiverId) REFERENCES Users(Id) ON DELETE CASCADE
);
